LARGE_TITLE_FONT = ("Arial", 20, "bold")
SMALL_TITLE_FONT = ("Arial", 16, "bold")


PADDING_SMALL = 2
PADDING_MEDIUM = 5
PADDING_LARGE = 10


APP_DIMENSIONS = (650, 900)
APP_HEIGHT, APP_WIDTH = APP_DIMENSIONS

MEDIUM_BUTTON_DIMENSIONS = (27, 30)
MEDIUM_BUTTON_HEIGHT, MEDIUM_BUTTON_WIDTH = MEDIUM_BUTTON_DIMENSIONS

ROW_BUTTON_DIMENSIONS = (30, 20)
ROW_BUTTON_HEIGHT, ROW_BUTTON_WIDTH = ROW_BUTTON_DIMENSIONS

WIDE_ROW_BUTTON_DIMENSIONS = (60, 20)
WIDE_ROW_BUTTON_HEIGHT, WIDE_ROW_BUTTON_WIDTH = WIDE_ROW_BUTTON_DIMENSIONS

SQUARE_BUTTON_DIMENSIONS = (25, 20)
SQUARE_BUTTON_HEIGHT, SQUARE_BUTTON_WIDTH = SQUARE_BUTTON_DIMENSIONS

FLAT_BUTTON_DIMENSIONS = (20, 10)
FLAT_BUTTON_HEIGHT, FLAT_BUTTON_WIDTH = FLAT_BUTTON_DIMENSIONS

CHECKBOX_DIMENSIONS = (18, 18)
CHECKBOX_HEIGHT, CHECKBOX_WIDTH = CHECKBOX_DIMENSIONS
CHECKBOX_BORDER_WIDTH = 2