### BUS PROPERTIES ###
MIN_BUS_TRACKING_NUM = 100
MAX_BUS_TRACKING_NUM = 999
MIN_BUS_YEAR = 1900
LAST_DATE_SEEN_UNKNOWN_PLACEHOLDER = "never"
NO_LOCATION_INFO_PLACEHOLDER = "No location information"

### RUN PROPERTIES ###
NUM_BLOCK_ID_TOKENS = 2

### LOCATION INFO PROPERTIES ###
MIN_LATITUDE = -90
MAX_LATITUDE = 90
MIN_LONGITUDE = -180
MAX_LONGITUDE = 180

MIN_STOP_ID = 10000
MAX_STOP_ID = 99999

### TIME CONSTANTS ###
HOURS_PER_DAY = 24
MINUTES_PER_HOUR = 60
SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = MINUTES_PER_HOUR * SECONDS_PER_MINUTE
MILLISECONDS_PER_SECOND = 1000

### LOCATION FETCH POLLING ###
DEFAULT_POLLING_INTERVAL_MINUTES = 30
MIN_POLLING_INTERVAL_MINUTES = 15
